load_module modules/ngx_http_brotli_static_module.so;

worker_processes auto;
events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;
    sendfile      on;

    server {
        listen 80;
        server_name _;
        root /usr/share/nginx/html;

        add_header X-Frame-Options "SAMEORIGIN" always;
        add_header X-Content-Type-Options "nosniff" always;
        add_header Referrer-Policy "strict-origin-when-cross-origin" always;
        add_header Strict-Transport-Security "max-age=63072000; includeSubDomains" always;
        add_header Content-Security-Policy "default-src 'self'; script-src 'self' https://data.bitstorm.org; connect-src 'self' https://data.bitstorm.org; img-src 'self'; font-src 'self'; style-src 'self' 'sha256-+3winYRwX8iPrZErB/Cw4ytcS8Y7XBtE5nx+fw7Qo9E='; manifest-src 'self'; object-src 'none'; base-uri 'self'; frame-ancestors 'none'; form-action 'self'; upgrade-insecure-requests" always;

        brotli_static on;

        location / {
            try_files $uri $uri/ /index.html;
        }

        location ~* \.(?:woff2|webp|png)$ {
            expires 1y;
            add_header Cache-Control "public, immutable";
            access_log off;
        }

        location = /manifest.json {
            expires 1d;
            add_header Cache-Control "public, max-age=86400";
        }
    }
}