load_module modules/ngx_http_brotli_static_module.so;

worker_processes auto;
events { worker_connections 1024; }

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;
    sendfile      on;

    server {
        listen 80;
        server_name _;
        root /usr/share/nginx/html;

        brotli_static on;
        add_header Vary Accept-Encoding;

        location / {
            try_files $uri $uri/ /index.html;
        }
    }
}